[platformio]
default_envs = cncrouter
src_dir = src

[env]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

[env:cncrouter]
build_src_filter = +<EquipmentSenderEntry.cpp>
build_flags = -D EQUIPMENT_PROFILE_CNC_ROUTER

[env:tablesawplaner]
build_src_filter = +<EquipmentSenderEntry.cpp>
build_flags = -D EQUIPMENT_PROFILE_TABLE_SAW_PLANER

[env:jointer]
build_src_filter = +<EquipmentSenderEntry.cpp>
build_flags = -D EQUIPMENT_PROFILE_JOINTER

[env:worktable]
build_src_filter = +<EquipmentSenderEntry.cpp>
build_flags = -D EQUIPMENT_PROFILE_WORK_TABLE

[env:dustcollector]
build_src_filter = +<DustCollectorEntry.cpp>

[env:barrelmonitor]
build_src_filter = +<BarrelMonitorEntry.cpp>
lib_deps = adafruit/Adafruit_VL53L0X
